     lib/
       app/
       feature_meal_discovery/
       feature_meal_plan_builder/
       feature_recipe_details/
       feature_nutrition_tracking/
       feature_product_scan/
       feature_health_scoring/
       feature_alternatives/
       feature_shopping_list/
       feature_auth/
       feature_user_profile/
       feature_preferences/
       feature_retail_integration/
       feature_crowdsourcing/
       feature_admin_tools/
       feature_notifications/
       feature_search/
       feature_offline_cache/